# Generated by Django 5.1.4 on 2025-01-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
